name: Deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        cd $GITHUB_WORKSPACE/src
        mv confidentialTemplate.json confidential.json
    - name: Install node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Compile typescript
      run: |
        cd $GITHUB_WORKSPACE
        ./node_modules/.bin/tsc -p tsconfig.json
        cp app.yaml build/app.yaml
    - name: Install gcloud CLI
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: Deploy glcoud App Engine
      run: |
        cd $GITHUB_WORKSPACE/build
        gcloud app deploy --quiet
